"""
This type stub file was generated by pyright.
"""

import datetime
import json
import typing
import pydantic
import rel
from websocket._app import WebSocketApp

def on_message(ws: WebSocketApp, message: bytes, strategy_handler: typing.Callable[[WebSocketApp, typing.Any], typing.Any]) -> None:
    ...

def on_error(ws: WebSocketApp, error: str) -> None:
    ...

def on_close(ws: WebSocketApp, close_status_code: str, close_msg: str) -> None:
    ...

def on_open(ws: WebSocketApp, token: str, device_token: str, asset_id: int) -> None:
    ...

class ReaderParams(pydantic.BaseModel):
    url: str
    token: str
    device_token: str
    asset_id: int
    on_message_strategy: typing.Callable[[WebSocketApp, bytes], typing.Any]
    ...


def read(main_args: ReaderParams) -> None:
    ...

