"""
This type stub file was generated by pyright.
"""

import typing

OriginalFunction = typing.Callable[..., typing.Any]
CallbackFunction = typing.Callable[[Exception], typing.Any]
Wrapper = typing.Callable[..., typing.Any]
Decorator = typing.Callable[[Wrapper], Wrapper]
class EoprError(Exception):
    """Exception raised when an error occurs in the eopr library."""
    def __init__(self, e: Exception) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


def default_error_callback(e: Exception) -> typing.NoReturn:
    ...

def error_handler(callback: CallbackFunction) -> Decorator:
    ...

