"""
This type stub file was generated by pyright.
"""

import typing
import pydantic
from eopr.core.indicators.common import CandlePrice, FloatArray, TrendAnalysis

MACDLine = FloatArray
SignalLine = FloatArray
Histogram = FloatArray
Interpretation = str
class MACDParameters(pydantic.BaseModel):
    prices: list[CandlePrice]
    fast: int
    slow: int
    signal: int
    err_handler: typing.Callable[[Exception], None] = ...


class MACDIndicator(pydantic.BaseModel):
    macd_line: MACDLine
    signal_line: SignalLine
    histogram: Histogram
    analysis: TrendAnalysis
    err_handler: typing.Callable[[Exception], None] = ...


def ema(prices: FloatArray, period: int) -> FloatArray:
    ...

def macd(macd_params: MACDParameters) -> MACDIndicator:
    ...

def interpret_macd(macd: MACDIndicator) -> MACDIndicator:
    """Interpret the MACD indicator.

    This function takes as input the MACD line, the signal line, and the histogram. It
    determines the trends of these lines by comparing their last two values. If the last
    value is greater than the second-to-last value, the trend is considered to be
    “rising”. Otherwise, it is considered to be “falling”.

    The function also calculates the distance between the MACD and signal lines by
    taking the absolute value of their difference. This distance can be used to gauge
    the strength of the current trend.

    Finally, the function returns a string that describes the current trends of the MACD
    line, signal line, and histogram. This string includes information about whether
    these lines are rising or falling, as well as information about the distance between
    the MACD and signal lines.

    Args:
        macd_line (FloatArray): The MACD line values.
        signal_line (FloatArray): The signal line values.
        histogram (FloatArray): The histogram values.

    Returns:
        str: The interpretation of the MACD indicator.
    """
    ...

